language: node_js
node_js:
- 10.16.0
install:
- npm install -g codecov
- npm install --ignore-scripts
script:
- npm run test -- "--coverage"
- codecov --token=b0fd890e-36fd-4395-8591-9054d978f917
- npm pack
deploy:
- provider: npm
  email: fdf8210@gmail.com
  api_key:
    secure: rm1JYf5xEkkCRLgdAsMjMC0qQTkKijq+NjXe1ZA6x9IDzCGNeo7L0GAOTK0O4B1Oo1N11HNdBDeDDN7TPpJtJeMdLHN2XDdj1o5wAbfdImZ7yjxkiw/4x1SRy32/kESdDINjGRN9ea9RGSZVKIOWC9liehZvnWVxHdklHFoeiZljQQcqQfCZ5hpD+zVuTa7RZmpi9iF0vtLVO5fa1ZIIZlDOvgo1iP0WEi8d9sTW4STvbYSjZiwrF5rVSabL1Phgk2Bi8F5BkUhziLWnpInWgabaGh7XPdsOhqrypQ/h1BR9bSDO3t/Fu845J4MDstBBX6Olk09vZdqj7H9F4cpDpf6TPNnLuqjtZs9G+2xw5DEx5M7/7olgjORt8Ixjjo+Ac/4sLXHyTo0fjUNm6z2gtc+XJDj8n4rsyx+rklDxcLngpgr5jBdyfpRKoUJJxtg6dPiHybggJtZoS/bvbTM8bZSBxmy/13ZHR+Odr79fpHDCfbX8bhyygINUS1pLk3bJH7B1YuHAKTPj5kE3Ogr5HXM3Uao5/+y/sjm/z3BOXNvjxw/DMJfSw66CEqMJzhq315cmOpQm6nTCzPPgw9woVLGc+UyTS9b7QJuh4guoev4kyJm0VQXTT5CGj/hG50HGZLTYg45lAck6ATqrHAFPZka+Yzy5qYOqxMEFNM7wDPU=
  on:
    repo: fdefelici/react-bootstrap-combobox
    tags: true
  skip_cleanup: true
- provider: releases
  api_key:
    secure: JFxwOQlDSq+A2JaQLsRYpoFb1Cv+rJs4ENQwkVe3er/SneDvYpbcffWJed8zngkuwtmTKfXmXqs7i2tWLfT4bxAh2BnYeldngLVjQ+BJSmOvjHRH9oJhF56+XBMjXXskSqSZGyPDJI+rw0iEYtgt6BNK2faX5jtP7yptvIgWRHLwFq+I6ynOuFt6pxJfpmAaOJD89sbGv7FwNAHyHMxcCafrU+iUU+rjNCFX662o0zhi3LiKEhlGpQrh5iLh4yp3vbllAE2FBreqDhnKsqNz6AcUmQFbLqnc2Sw2gFUgs2My1rAKsoc3Re2NfQipPn1XD/dc99/iqsKWAHkQGNV/WZgE6oS2IhOl7T48PHx8ifSJ+3nbUrKM0hQdmZNOLtDYRY+/7lqPrJnAz5/J3Oqsb0itMMiVuzNLsgOnLlv7jwr/Ke8bceA72KWsjpIA5lUPVUj+Tz6qqqRtvaB0CjGH9ajGnzfhSUsdAnSQWgAv25BDyvLZAhHxW5ioaaRpCV4HPdSItVk+7SQ1NjA2txRHS7JDHQagxd6/YU8Td7wBMdGlIfPX2M30869HVYzPW/A8BsFclO7Nwj6Lg+EYq2z1pFhob1t9C3WdbstO3N+HSzm3euQIvq0uKXXACs2tdJCLHgmqlkyQwTdrG1JlsO53lUSnqrPkhphWwhSER8e6Ttg=
  file_glob: true
  file: fdefelici-react-bootstrap-combobox-*.tgz
  on:
    repo: fdefelici/react-bootstrap-combobox
    tags: true
  skip_cleanup: true