language: node_js
node_js:
- 10.16.0
install:
- npm install -g codecov
- npm install --ignore-scripts
script:
- npm run test -- "--coverage"
- codecov --token=b0fd890e-36fd-4395-8591-9054d978f917
- npm run build
- echo "FILESYSTEM:"
- ls -l
deploy:
  provider: npm
  email: fdf8210@gmail.com
  api_key:
    secure: rm1JYf5xEkkCRLgdAsMjMC0qQTkKijq+NjXe1ZA6x9IDzCGNeo7L0GAOTK0O4B1Oo1N11HNdBDeDDN7TPpJtJeMdLHN2XDdj1o5wAbfdImZ7yjxkiw/4x1SRy32/kESdDINjGRN9ea9RGSZVKIOWC9liehZvnWVxHdklHFoeiZljQQcqQfCZ5hpD+zVuTa7RZmpi9iF0vtLVO5fa1ZIIZlDOvgo1iP0WEi8d9sTW4STvbYSjZiwrF5rVSabL1Phgk2Bi8F5BkUhziLWnpInWgabaGh7XPdsOhqrypQ/h1BR9bSDO3t/Fu845J4MDstBBX6Olk09vZdqj7H9F4cpDpf6TPNnLuqjtZs9G+2xw5DEx5M7/7olgjORt8Ixjjo+Ac/4sLXHyTo0fjUNm6z2gtc+XJDj8n4rsyx+rklDxcLngpgr5jBdyfpRKoUJJxtg6dPiHybggJtZoS/bvbTM8bZSBxmy/13ZHR+Odr79fpHDCfbX8bhyygINUS1pLk3bJH7B1YuHAKTPj5kE3Ogr5HXM3Uao5/+y/sjm/z3BOXNvjxw/DMJfSw66CEqMJzhq315cmOpQm6nTCzPPgw9woVLGc+UyTS9b7QJuh4guoev4kyJm0VQXTT5CGj/hG50HGZLTYg45lAck6ATqrHAFPZka+Yzy5qYOqxMEFNM7wDPU=
  on:
    tags: true
    repo: fdefelici/react-bootstrap-combobox
  skip_cleanup: true
